local Aimbot = Instance.new("ScreenGui")
local TextLabel = Instance.new("TextLabel")
rs = game:GetService("RunService")
local Mouse = game.Players.LocalPlayer:GetMouse()
local uis = game:GetService("UserInputService")
local shootanim = "rbxassetid://9863626369"
holdx = false



Aimbot.Name = "Aimbot"
Aimbot.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
Aimbot.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
Aimbot.ResetOnSpawn = false

TextLabel.Parent = Aimbot
TextLabel.BackgroundColor3 = Color3.new(0.444511, 0.771695, 0.998947)
TextLabel.BorderColor3 = Color3.new(0.39057, 0.39057, 0.39057)
TextLabel.BorderSizePixel = 2
TextLabel.Position = UDim2.new(0.75, 0, 0.75, 0)
TextLabel.Size = UDim2.new(0, 132, 0, 50)
TextLabel.Font = Enum.Font.Code
TextLabel.Text = "Target: Nil"
TextLabel.TextColor3 = Color3.new(255,204,0)
TextLabel.TextScaled = false
TextLabel.TextSize = 17
TextLabel.TextWrapped = true
TextLabel.BackgroundTransparency = 1


Mouse.KeyDown:Connect(function(key)
    if key == "q" then
        if Mouse.Target.Parent:FindFirstChild("Humanoid") then
        
getgenv().Target = TextLabel.Text
               print(getgenv().Target)

            TextLabel.Text = Mouse.Target.Parent.Name
        end
        if Mouse.Target.Parent:IsA("Accessory") then
            TextLabel.Text = Mouse.Target.Parent.Parent.Name
             getgenv().
Target = TextLabel.Text
            print(getgenv().Target)

        end
    end
end)


getgenv().rs = game:GetService("RunService")
getgenv().pbOn = false
local LocalP = game.Players.LocalPlayer
local prev = game.Players.LocalPlayer.Character:WaitForChild('HumanoidRootPart').CFrame

local prefix = "."
local LPlayer = game.Players.LocalPlayer
LPlayer.Chatted:Connect(function(msg)
	msg = msg:lower()
	if string.sub(msg,1,3) == "/e " then
		msg = string.sub(msg,4)
	end
	if string.sub(msg,1,1) == prefix then
		local cmd
		local space = string.find(msg," ")
		if space then
			cmd = string.sub(msg,2,space-1)
		else
			cmd = string.sub(msg,2)
		end




		if cmd == "spb" then
			getgenv().pbOn = false
		end
	end
end)
LPlayer.Chatted:Connect(function(msg)
	msg = msg:lower()
	if string.sub(msg,1,3) == "/e " then
		msg = string.sub(msg,4)
	end
	if string.sub(msg,1,1) == prefix then
		local cmd
		local space = string.find(msg," ")
		if space then
			cmd = string.sub(msg,2,space-1)
		else
			cmd = string.sub(msg,2)
		end




		if cmd == "pb" then
		game:GetService("Players").LocalPlayer.Backpack.Pipe.Parent = game:GetService("Workspace"):FindFirstChild(game.Players.LocalPlayer.Name)
print('has')
			getgenv().pbOn = true
		end
	end
end)

event = rs.RenderStepped:Connect(function()
if getgenv().pbOn == true then
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game.Players:FindFirstChild(Target).Character.Torso.CFrame+game.Players:FindFirstChild(Target).Character.HumanoidRootPart.Velocity/8.2

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character.Pipe,
    [2] = game:GetService("Players").LocalPlayer.Character.Pipe.Handle,
    [3] = false,
    [4] = true
}

game:GetService("Players").LocalPlayer.Backpack.ServerTraits.Touch:FireServer(unpack(args))
game.Players.LocalPlayer.Backpack.ServerTraits.Finish:FireServer(game.Players.LocalPlayer.Backpack:FindFirstChild'Punch' or game.Players.LocalPlayer.Character:FindFirstChild'Punch')
if game:GetService("Workspace"):FindFirstChild(LocalP.Name):FindFirstChild("KO") then
    prev = LocalP.Character:WaitForChild('HumanoidRootPart').CFrame
        LocalP.Character.Parent = workspace.Terrain
        LocalP.Character.Torso:Destroy()
        game:GetService('Workspace'):WaitForChild(LocalP.Name) 
        for i=1,10 do
            LocalP.Character:WaitForChild('HumanoidRootPart').CFrame = prev
            wait()
		game:GetService("Players").LocalPlayer.Backpack.Pipe.Parent = game:GetService("Workspace"):FindFirstChild(game.Players.LocalPlayer.Name)
        end
end


end

if getgenv().pbOn == false then
Target = nil
end






end)
